/**
 * designSignalWiring.test.ts — REGRESSION-CLASS tripwires for the 2026-08-09 dead wire.
 * ─────────────────────────────────────────────────────────────────────────────────────
 * THE BUG THIS EXISTS TO MAKE UNREPEATABLE. `applyRelevanceGate` selected
 * `'product_title, design_name_override, audience_lean'` from listing_seo_scores and then read
 * `scoreRow.design_name_overrides` — a column it had never selected. The expression was therefore
 * ALWAYS undefined, so every MULTI-DESIGN family (scalar null + per-design map populated, which is
 * exactly what the design-name UI writes) resolved zero design names ⇒ no theme card ⇒ an empty
 * rating map ⇒ theme_fit NULL on all 86 rows ⇒ a target set ordered on market score alone. It ran
 * for months and cost nothing in tsc: the field is optional on every type it passes through, and the
 * read site casts to an inline `{ design_name_overrides?: ... }` shape that invents the property.
 *
 * WHY THESE ARE SOURCE-TEXT ASSERTIONS AND NOT BEHAVIOURAL ONES. The defect lives in a STRING —
 * a PostgREST select list — that no type can constrain and no unit test can exercise without a live
 * database. A literal assertion on that string is the only thing that can fail when someone edits it
 * back. Deliberately narrow: each checks ONE column name in ONE select list, so it cannot become a
 * brittle snapshot of the file.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const read = (...parts: string[]) => readFileSync(join(process.cwd(), 'src', ...parts), 'utf8')

describe('the listing_seo_scores select MUST carry BOTH design-name columns', () => {
  /** Every `.select('...')` argument in a file, as raw strings. */
  const selectLists = (src: string): string[] =>
    [...src.matchAll(/\.select\(\s*'([^']*)'/g)].map((m) => m[1])

  it('syncKeywordIntelligence: the relevance-gate score-row select includes design_name_overrides', () => {
    const lists = selectLists(read('lib', 'sync', 'syncKeywordIntelligence.ts'))
    const scoreSelects = lists.filter((l) => l.includes('design_name_override'))
    expect(scoreSelects.length).toBeGreaterThan(0)
    for (const list of scoreSelects) {
      // The PLURAL column — the one that was missing. `design_name_override` is a prefix of
      // `design_name_overrides`, so a naive includes() would pass on the broken string; assert the
      // plural explicitly.
      expect(list).toContain('design_name_overrides')
    }
  })

  it('selectionContext: its own re-query still selects both columns (the fallback path)', () => {
    const lists = selectLists(read('lib', 'keyword-engine', 'selectionContext.ts'))
    const scoreSelects = lists.filter((l) => l.includes('design_name_override'))
    expect(scoreSelects.length).toBeGreaterThan(0)
    for (const list of scoreSelects) expect(list).toContain('design_name_overrides')
  })

  it('loadSelectionContext re-queries a supplied row that is MISSING a design-name column', () => {
    // The structural supply check. `if (!scoreRow)` saw a truthy partial object and skipped the
    // re-query, which is what let the dead wire survive a loader that could have healed it.
    const src = read('lib', 'keyword-engine', 'selectionContext.ts')
    expect(src).toContain("'design_name_overrides' in scoreRow")
  })

  it('the theme card is fed from the loader\'s resolved sources, not a second narrower read', () => {
    const src = read('lib', 'sync', 'syncKeywordIntelligence.ts')
    expect(src).toContain('loadSelectionContextWithSources')
    // The card must read the SAME object the seasons were derived from.
    expect(src).toMatch(/designNameOverrides:\s*sources\.designNameOverridesByKey/)
    expect(src).toMatch(/visionDesignTheme:\s*sources\.visionDesign/)
    expect(src).toMatch(/resolvedDesignName:\s*sources\.resolvedDesignName/)
  })
})

describe('a RESEARCH SEED is a market question, never published text', () => {
  /**
   * `selectSeeds` used to run `scrubTrademarks` on every seed before it reached Jungle Scout, so a
   * design whose subject is a protected mark asked the market about a phrase no shopper types and
   * harvested NONE of its own keywords. The scrub belongs at the publish boundary — which is
   * separately defended in listingPipeline and pushExecutor on every generated byte.
   *
   * Asserted on source text for the same reason as above: the fix is the ABSENCE of a call, and
   * absence is not observable from outside without a live Jungle Scout + OpenAI.
   */
  const src = read('lib', 'keyword-engine', 'keywordResearcher.ts')

  it('the four seed paths do not scrub', () => {
    for (const line of [
      /if \(manualSeed\) return \{ seeds: \[manualSeed\]/,
      /if \(categorySeed\) return \{ seeds: \[categorySeed\]/,
      /const rulesSeed = buildSeedFromTitle\(/,
      // `\s*$` (multiline) absorbs the CR — this repo checks out CRLF.
      /const valid = validateSeeds\(.*productWord\)\s*$/m,
    ]) expect(src).toMatch(line)
  })

  it('no seed path pipes through scrubTrademarks any more', () => {
    expect(src).not.toMatch(/seeds: \[scrubTrademarks/)
    expect(src).not.toMatch(/scrubTrademarks\(buildSeedFromTitle/)
    expect(src).not.toMatch(/validateSeeds\([^)]*\)\.map\(scrubTrademarks\)/)
  })

  it('the Seed Agent is told to use the words shoppers really type', () => {
    expect(src).toContain('this is a market-research query, never published text')
    expect(src).not.toContain('NEVER use a protected TRADEMARK')
  })

  it('the S2 design-guarantee no longer bans a design whose own subject is a protected mark', () => {
    // S2 is the stratum that protects the design's own terms from the volume auction. Gating it on
    // hasTrademark denied the guarantee to precisely the designs that needed it most.
    expect(src).toMatch(/s2Gate: \(kw\) => !isForeignKeyword\(kw\) && !isCategoryGenericOnly\(kw\)/)
  })

  it('the PUBLISH boundary still scrubs — this change moved the net, it did not remove it', () => {
    const pipeline = read('lib', 'fba', 'listingPipeline.ts')
    const push = read('lib', 'fba', 'pushExecutor.ts')
    expect(pipeline).toContain('scrubTrademarks')
    expect(push).toContain('scrubTrademarks')
    // The terminal published-field door.
    expect(pipeline).toMatch(/scrubCelebrityNames\(scrubTrademarks\(/)
  })
})
