/**
 * One-time migration: Add keyword_reconciliation JSONB column to listing_seo_recommendations.
 * POST /api/admin/migrate-reconciliation
 *
 * This column stores the per-keyword placement map generated by the AI recommendations engine.
 * Run once after deploy, then this route can be removed.
 */

import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export async function POST() {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )

  const results: string[] = []

  // Check if column already exists by trying to select it
  const { error: checkErr } = await supabase
    .from('listing_seo_recommendations')
    .select('keyword_reconciliation')
    .limit(1)

  if (!checkErr) {
    return NextResponse.json({
      message: 'keyword_reconciliation column already exists',
      results: ['✓ Column exists — no migration needed'],
    })
  }

  // Column doesn't exist — try to add it via RPC
  // Supabase REST API can't ALTER TABLE, so we use the exec_sql RPC if available
  try {
    const { error: rpcErr } = await supabase.rpc('exec_sql', {
      sql: `ALTER TABLE listing_seo_recommendations ADD COLUMN IF NOT EXISTS keyword_reconciliation JSONB DEFAULT '[]'::jsonb;`,
    })

    if (rpcErr) {
      results.push(`RPC exec_sql failed: ${rpcErr.message}`)
      results.push('Please run this SQL manually in Supabase SQL Editor:')
      results.push(`ALTER TABLE listing_seo_recommendations ADD COLUMN IF NOT EXISTS keyword_reconciliation JSONB DEFAULT '[]'::jsonb;`)
    } else {
      results.push('✓ keyword_reconciliation column added successfully')
    }
  } catch (err) {
    results.push(`Error: ${err instanceof Error ? err.message : String(err)}`)
    results.push('Please run this SQL manually in Supabase SQL Editor:')
    results.push(`ALTER TABLE listing_seo_recommendations ADD COLUMN IF NOT EXISTS keyword_reconciliation JSONB DEFAULT '[]'::jsonb;`)
  }

  return NextResponse.json({ results })
}
