-- 049_keyword_target_set.sql
-- 048_push_jobs_cancel.sql is the highest applied. 047 does NOT exist (numbering is chronological,
-- not dense) — do NOT reuse it. Apply BY HAND in the Supabase SQL editor, BEFORE the deploy.
--
-- KEYWORD_TARGET_SET. Today tier membership is pure arithmetic on opportunity_score
-- (engine.ts:310-325), and opportunity_score is PRESENCE-AMPLIFIED (calculateScore.ts:176-179 over
-- checkPresence.ts:150-161), so a keyword we will never cover carries a permanent x3 premium:
-- "art teacher clothes" (5,331/mo, opp 53) outranks "comfort colors tshirt" (306,496/mo, opp 14)
-- on B0GF49RLDL purely BECAUSE we do not cover it. No relevance classifier can out-argue that
-- arithmetic, which is why PRs #441/#442 (RELEVANCE_THEME_V2) caught zero on a live re-research.
--
-- theme_fit is a JUDGMENT SIGNAL (LLM). selection_rank is a DERIVED SELECTION (pure deterministic
-- function of the signals + raw market math, recomputed on every storeAnalysis). action_type is
-- NEVER rewritten: there is no IRRELEVANT-style ratchet here (ai-recommendations/route.ts:903-907
-- has no reverse path anywhere in the codebase and once permanently demoted a seller's top money
-- keyword). Additive + nullable: with KEYWORD_TARGET_SET=off every read is byte-identical to today.

ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS theme_fit        smallint;
ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS theme_about      text;
ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS theme_run_id     text;
ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS selection_rank   smallint;
ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS selection_slot   text;
ALTER TABLE keyword_analysis ADD COLUMN IF NOT EXISTS selection_reason text;

DO $$ BEGIN
  ALTER TABLE keyword_analysis ADD CONSTRAINT ck_keyword_theme_fit
    CHECK (theme_fit IS NULL OR theme_fit BETWEEN 0 AND 3);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE keyword_analysis ADD CONSTRAINT ck_keyword_selection_slot
    CHECK (selection_slot IS NULL OR selection_slot IN ('CORE','CATEGORY','BACKEND'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_keyword_analysis_target
  ON keyword_analysis (asin, selection_rank)
  WHERE selection_rank IS NOT NULL;

-- The theme card is PERSISTED and PO-EDITABLE rather than regenerated inside every rating call.
-- A resampled free-text card would re-condition every rating on ~12 fresh tokens and make the
-- target set churn run-to-run with no seller-visible cause. theme_card_sig =
-- sha1(design_name_override || json(design_name_overrides) || audience_lean); a mismatch
-- regenerates the card, a match reuses it. Editing theme_card by hand is the PO override lever.
ALTER TABLE listing_seo_scores ADD COLUMN IF NOT EXISTS theme_card     text;
ALTER TABLE listing_seo_scores ADD COLUMN IF NOT EXISTS theme_card_sig text;

COMMENT ON COLUMN keyword_analysis.theme_fit IS
  'KEYWORD_TARGET_SET ordinal 0-3 (3=CORE theme, 2=CATEGORY-UNIVERSAL, 1=GENERIC, 0=OFF-PRODUCT). Per-index MEDIAN of 3 LLM raters. An ORDINAL BAND, not a float: medians over bands are stable run-to-run, medians over floats are not. NULL = never rated; the selector treats NULL as band 2 and NEVER hard-gates it — unrated is not off-theme.';
COMMENT ON COLUMN keyword_analysis.theme_about IS
  'The raters 1-3 word description of what the shopper typing this keyword wants ("art teachers", "concert merch"). Written BEFORE the band, which is what makes an on-theme rating for an off-theme keyword a self-evident contradiction. Surfaced in the Intelligence tab.';
COMMENT ON COLUMN keyword_analysis.theme_run_id IS
  'Rater run identifier (kt_<epoch>_<rand>). Lets a bad rating batch be found and re-run, and feeds the rankAnalysis contentFingerprint so cached playbooks self-invalidate when the signals change.';
COMMENT ON COLUMN keyword_analysis.selection_rank IS
  'THE one membership predicate: NOT NULL = ranking target, NULL = pooled but not a target. 1..30, dense. Recomputed by selectRankingTargets on EVERY storeAnalysis, so it is a derived mirror and never a persisted demotion. Score cards, RANK panel, Intelligence tab and every generator derive "is this a target?" from THIS COLUMN and nothing else — never from action_type arithmetic.';
COMMENT ON COLUMN keyword_analysis.selection_slot IS
  'CORE | CATEGORY | BACKEND. BACKEND = seasonal or otherwise structurally unplaceable in title/bullets (six of seven generators hard-strip SEASONAL_TERMS at listingPipeline.ts:244-252), so BACKEND targets are EXEMPT from the keyword_score dock and from RANK-panel ADD advice. Ranking for a phrase the copy must never contain is a dock no regenerate can clear.';
COMMENT ON COLUMN keyword_analysis.selection_reason IS
  'DETERMINISTIC prose generated by the selectors own decision path (never LLM text): "CORE rank 4/14 - market 61.2 x theme 1.00", "off-theme: art teachers (3/3 raters)", "volume backstop (821,120/mo)", "eligible, CATEGORY slot full at rank 11/10". Revives AnalyzedKeyword.rationale (declared engine.ts:88, hardcoded empty at cacheService.ts:183, never rendered).';
COMMENT ON COLUMN listing_seo_scores.theme_card IS
  'One-line authoritative design theme, e.g. "Valentines Day cupid romance love gift graphic tee for women". Generated once from the design name(s) + audience lean, then PERSISTED. PO-EDITABLE: edit this row by hand to override the rater context; it sticks until theme_card_sig changes.';
COMMENT ON COLUMN listing_seo_scores.theme_card_sig IS
  'sha1(design_name_override || json(design_name_overrides) || audience_lean). Mismatch regenerates theme_card; match reuses it. This is what keeps the rater context STABLE run-to-run (the determinism requirement) while still reacting when the seller changes a design name.';

NOTIFY pgrst, 'reload schema';

-- CODE THAT MUST SHIP WITH THIS SQL (non-negotiable):
--   cacheService.ts missing-column fallback regex MUST list all 6 new keyword_analysis column
--   names, or deploying before the SQL is applied silently degrades EVERY native keyword sync
--   (the exact title_density / organic_rank precedent).
--
-- EXPLICITLY NO NEW TABLE, and keyword_plan is explicitly REJECTED as the home for selection:
-- it is keyed on parent_asin (the Intelligence tab and RANK panel both resolve to a CHILD and read
-- keyword_analysis), it is written only by the regen route, and it carries the live data-loss bug
-- at ai-recommendations/route.ts:788. It receives a DERIVED MIRROR only (keywordPlan.selected +
-- selectionSha, for scorer/provenance parity) and :788 is fixed in the same PR.
